### ISSUE TITLE
Do not access register elements via [0], [1], etc

### ISSUE THREAD

**Issue by robthebloke** [NCCA/SIMD#3]
https://nccastaff.bournemouth.ac.uk/jmacey/AProg/slides/SIMD/slides.html#/5/3

In your notes on page 52, you access the elements via [0], [1], etc. This will not compile on Win32 (the internals of registers are off limits, and are never specified, but they can never be accessed on the CPU). Clang/gcc allow you to away with this, but Win32 will not. 

Accessing registers in this way has some nasty side effects:

```c++
float getF0(__m128 a)
{
    return a[0];
}
float getF1(__m128 a)
{
    return a[1];
}
float getF2(__m128 a)
{
    return a[2];
}
float getF3(__m128 a)
{
    return a[3];
}
```
Produces the following assembly:

```asm
; zero cost cast, or _mm_cvtss_f32 
getF0(float __vector(4)):
 ret    

; swizzle + cast  _mm_cvtss_f32( _mm_movehdup_ps(a) )
getF1(float __vector(4)):
 vmovshdup xmm0,xmm0
 ret    

; _mm_cvtss_f32( _mm_movehl_ps(a) )
getF2(float __vector(4)):
 vpermilpd xmm0,xmm0,0x1
 ret    

; _mm_cvtss_f32( _mm_permute_ps(a, 0xe7) )
getF3(float __vector(4)):
 vpermilps xmm0,xmm0,0xe7
 ret    
```
Things get even nastier when you access elements 4 -> 7 in a __m256 (since it needs to do a 3 cycle permute128 prior the the code above). This kinda kills performance. 

The only cross OS way of doing this kinda thing is to add a utility func:

```c++
void print(__m128 a) 
{
    alignas(16) float f[4];
    _mm_store_ps(f, a);
    printf("%f %f %f %f", f[0], f[1], f[2], f[3]);
}
```
It's still produce the exact same crap asm, but it will work on windows as well. (also consider that on some platforms, e.g. arm/powerPC, the FPU registers exist in a different part of the CPU to the NEON/altivec registers. This causes a right bother performance wise)

**Comment by jmacey** [comment]
Have added more notes to the slides about this. Will leave the code in to help explain it.
