### ISSUE TITLE
float16 support

### ISSUE THREAD

**Issue by robthebloke** [NCCA/SIMD#4]
Add -mf16c to build options so you can access the float <-> half conversion intrinsics:

_mm256_cvtph_ps
_mm256_cvtps_ph

A much better approach that using the ILM half library!

(p.s. the SIMD wrappers on AL_USDMaya's git repo are moving today/tomorrow, and they'll be moving again in a few weeks time)

**Comment by jmacey** [comment]
Added functions and unit tests to the AVX demo
