### ISSUE TITLE
Corrections in notes

### ISSUE THREAD

**Issue by robthebloke** [NCCA/SIMD#7]
Page 67, typo: _mm_rcpps_ps
Also worth mentioning that rcp_ps and rsqrt_ps are _**approximations**_ to 1/x and 1/rsqrt(x) respectively (with terribly levels of accuracy, and the results differ wildly between cpu makes/models). Generally prefer division (normalising vertex normals may be ok with rsqrt, but normalising a ray within a ray tracer probably wouldn't be ok). (clang will replace divps with rcpps + newton raphson iteration). 

Page 76: the float array in the load4f test requires an alignas(16) 

Page 84: replace the 117 constant with hex. the mask to dot4f is easier to see, since the in/out masks are in each nibble of the byte.

**Comment by jmacey** [comment]
all done cheers
